// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbsrgmdfmskoseexaiiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ic3JnbWRmbXNrb3NlZXhhaWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzA3MzAsImV4cCI6MjA2NTcwNjczMH0.7qBiXerbAj1Y-7j6JMounrVvYS4l0BRnRS2BBwbf4RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);